### ISSUE TITLE
Update catalog on initial install?

### ISSUE THREAD

**Issue by elitest** [ephraim/lcurse#11]
Thank you so much for making this!

I might be able to send in a PR for this at some point, but what do you think of prompting to do an initial pull of the catalog when you first launch it?

**Comment by ephraim** [comment]
Yeah. Such a firsttime - wizard would be a nice thing... not only to do an initial update of the catalog but also to import the already installed addons and doing some settings like the wine folder a.s.o. .... 
I probably will do something like that one day ....
