### ISSUE TITLE
Stuck updating

### ISSUE THREAD

**Issue by Quintin96** [ephraim/lcurse#12]
On my initial start of lcurse, I clicked update catalog. This got stuck at 46%, I then restarted pc etc, still stuck at 46%. I then just cancelled it, imported my addons, and upon clicking update all addons, the "Verifying which addons need to be updated" also got stuck at 46%.

**Comment by ephraim** [comment]
Thats a nice one :).
Would you mind to share your addons and settings file?

~/.lcurse/addons.json
~/.lcurse/settings.cfg

Thanks.

**Comment by Quintin96** [comment]
addons.json:

[{"uri": "http://www.curse.com/addons/wow/burlex-core", "allowbeta": false, "name": "Burlex Core", "version": "5.0.0.10000"}, {"uri": "http://www.curse.com/addons/wow/chinchilla", "allowbeta": false, "name": "Chinchilla Minimap", "version": "v2.7.4"}, {"uri": "http://www.curse.com/addons/wow/metamapfwm", "allowbeta": false, "name": "MetaMapFWM", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/tidy-plates:-threat-plates", "allowbeta": false, "name": "Tidy Plates: Threat Plates", "version": "6.008"}, {"uri": "http://www.curse.com/addons/wow/atlasloot-enhanced", "allowbeta": false, "name": "AtlasLoot Enhanced", "version": "v8.00.51"}, {"uri": "http://www.curse.com/addons/wow/stat-block_fps", "allowbeta": false, "name": "StatBlock_FPS", "version": "r56-release"}, {"uri": "http://www.curse.com/addons/wow/spellflash-priest", "allowbeta": false, "name": "SpellFlash: Priest", "version": "1.10.13"}, {"uri": "http://www.curse.com/addons/wow/datastore_reputations", "allowbeta": false, "name": "DataStore_Reputations", "version": "r35"}, {"uri": "http://www.curse.com/addons/wow/deadly-boss-mods", "allowbeta": false, "name": "Deadly Boss Mods", "version": "6.1.9"}, {"uri": "http://www.curse.com/addons/wow/scrap-cleaner", "allowbeta": false, "name": "Scrap Cleaner", "version": "11"}, {"uri": "http://www.curse.com/addons/wow/guild-recruitment", "allowbeta": false, "name": "Guild Recruitment Helper", "version": "3.1"}, {"uri": "http://www.curse.com/addons/wow/auc:stat:histogram", "allowbeta": false, "name": "Auc:Stat:Histogram", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/spoilsofwar", "allowbeta": false, "name": "Spoils of War (Loot Browser)", "version": "r128"}, {"uri": "http://www.curse.com/addons/wow/bagnon-scrap", "allowbeta": false, "name": "Bagnon Scrap", "version": "14"}, {"uri": "http://www.curse.com/addons/wow/metamapqst", "allowbeta": false, "name": "MetaMapQST", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_warehousing", "allowbeta": false, "name": "TradeSkillMaster_Warehousing", "version": "v2.1.4"}, {"uri": "http://www.curse.com/addons/wow/datastore_crafts", "allowbeta": false, "name": "DataStore_Crafts", "version": "r67"}, {"uri": "http://www.curse.com/addons/wow/handynotes_lostandfound", "allowbeta": false, "name": "HandyNotes_LostAndFound", "version": "v9"}, {"uri": "http://www.curse.com/addons/wow/big-wigs", "allowbeta": false, "name": "BigWigs Bossmods", "version": "r13694-release"}, {"uri": "http://www.curse.com/addons/wow/altoholic", "allowbeta": false, "name": "Altoholic", "version": "r160"}, {"uri": "http://www.curse.com/addons/wow/guild-kicker", "allowbeta": false, "name": "Guild Kicker", "version": "Guild Kicker 1.2"}, {"uri": "http://www.curse.com/addons/wow/handynotes_guild", "allowbeta": false, "name": "HandyNotes_Guild", "version": "1.8"}, {"uri": "http://www.curse.com/addons/wow/handynotes-well-read", "allowbeta": false, "name": "HandyNotes: Well Read", "version": "6.1.0.4"}, {"uri": "http://www.curse.com/addons/wow/milling", "allowbeta": false, "name": "Milling", "version": "Milling_6.0"}, {"uri": "http://www.curse.com/addons/wow/garrison-mission-manager", "allowbeta": false, "name": "Garrison Mission Manager", "version": "v30"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_itemtracker", "allowbeta": false, "name": "TradeSkillMaster_ItemTracker", "version": "v2.1.4"}, {"uri": "http://www.curse.com/addons/wow/npcscan-overlay", "allowbeta": false, "name": "_NPCScan.Overlay", "version": "6.1.2.4"}, {"uri": "http://www.curse.com/addons/wow/handynotes_lunarfestival", "allowbeta": false, "name": "HandyNotes_LunarFestival", "version": "v1.3"}, {"uri": "http://www.curse.com/addons/wow/spellflash", "allowbeta": false, "name": "SpellFlash", "version": "6.22"}, {"uri": "http://www.curse.com/addons/wow/datastore_achievements", "allowbeta": false, "name": "DataStore_Achievements", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/npcscan", "allowbeta": false, "name": "_NPCScan", "version": "6.1.2.3"}
, {"uri": "http://www.curse.com/addons/wow/master-plan", "allowbeta": false, "name": "Master Plan", "version": "0.48"}, {"uri": "http://www.curse.com/addons/wow/weakauras-2", "allowbeta": false, "name": "WeakAuras 2", "version": "2.1.0.16"}, {"uri": "http://www.curse.com/addons/wow/datastore_stats", "allowbeta": false, "name": "DataStore_Stats", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/metamaptrk", "allowbeta": false, "name": "MetaMapTRK", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/postal", "allowbeta": false, "name": "Postal", "version": "v3.5.5"}, {"uri": "http://www.curse.com/addons/wow/bagnon-guild-bank", "allowbeta": false, "name": "Bagnon Guild Bank", "version": "6.1.7"}, {"uri": "http://www.curse.com/addons/wow/ace3", "allowbeta": false, "name": "Ace3", "version": "Release-r1134"}, {"uri": "http://www.curse.com/addons/wow/mogit", "allowbeta": false, "name": "MogIt", "version": "3.5.1"}, {"uri": "http://www.curse.com/addons/wow/datastore_inventory", "allowbeta": false, "name": "DataStore_Inventory", "version": "r42"}, {"uri": "http://www.curse.com/addons/wow/metamaphlp", "allowbeta": false, "name": "MetaMapHLP", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/gatherer", "allowbeta": false, "name": "Gatherer", "version": "5.0.0"}, {"uri": "http://www.curse.com/addons/wow/inspect-equip", "allowbeta": false, "name": "InspectEquip", "version": "2.0.9"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_crafting", "allowbeta": false, "name": "TradeSkillMaster_Crafting", "version": "v2.6.18"}, {"uri": "http://www.curse.com/addons/wow/swatter-(lib)", "allowbeta": false, "name": "Swatter (lib)", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/handynotes_treasurehunter", "allowbeta": false, "name": "HandyNotes_TreasureHunter", "version": "v8"}, {"uri": "http://www.curse.com/addons/wow/handynotes_lorewalkers", "allowbeta": false, "name": "HandyNotes_Lorewalkers", "version": "v5"}, {"uri": "http://www.curse.com/addons/wow/spellflash_racials", "allowbeta": false, "name": "BigRedBrent's SpellFlash: Racials", "version": "2.6.13"}, {"uri": "http://www.curse.com/addons/wow/tiptactalents", "allowbeta": false, "name": "TipTacTalents", "version": "15.03.04"}, {"uri": "http://www.curse.com/addons/wow/omen-threat-meter", "allowbeta": false, "name": "Omen Threat Meter", "version": "v3.1.10"}, {"uri": "http://www.curse.com/addons/wow/handy-notes_carbonite", "allowbeta": false, "name": "HandyNotes_Carbonite", "version": "V0.0.1 BETA"}, {"uri": "http://www.curse.com/addons/wow/minimalist", "allowbeta": false, "name": "Minimalist", "version": "r129"}, {"uri": "http://www.curse.com/addons/wow/datastore_currencies", "allowbeta": false, "name": "DataStore_Currencies", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/bitten-common", "allowbeta": false, "name": "Bitten's SpellFlash Library", "version": "60100.201503092107"}, {"uri": "http://www.curse.com/addons/wow/datastore_spells", "allowbeta": false, "name": "DataStore_Spells", "version": "r25"}, {"uri": "http://www.curse.com/addons/wow/raven", "allowbeta": false, "name": "Raven", "version": "r336"}, {"uri": "http://www.curse.com/addons/wow/timelessisle_RareElites", "allowbeta": false, "name": "HandyNotes_TimelessIsle_RareElites", "version": "2.31"}, {"uri": "http://www.curse.com/addons/wow/stat-block_latency", "allowbeta": false, "name": "StatBlock_Latency", "version": "r48-release"}, {"uri": "http://www.curse.com/addons/wow/stat-block-core", "allowbeta": false, "name": "StatBlockCore", "version": "r65-release"}, {"uri": "http://www.curse.com/addons/wow/scrap-spotlight", "allowbeta": false, "name": "Scrap Spotlight", "version": "12.24"}, {"uri": "http://www.curse.com/addons/wow/auc:filter:basic", "allowbeta": false, "name": "Auc:Filter:Basic", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/alternate-buttons-template", "allowbeta": false, "name": "Alternate Buttons Template", "version": "0.7.10"}, {"uri": "http://www.curse.com/
addons/wow/spellflash_druid", "allowbeta": false, "name": "SpellFlash: Druid", "version": "6.4.40"}, {"uri": "http://www.curse.com/addons/wow/tukui", "allowbeta": false, "name": "Tukui", "version": "16.21"}, {"uri": "http://www.curse.com/addons/wow/bonusrollpreview", "allowbeta": false, "name": "BonusRollPreview", "version": "60100-25-Release"}, {"uri": "http://www.curse.com/addons/wow/face-smasher", "allowbeta": false, "name": "Face Smasher", "version": "2.032"}, {"uri": "http://www.curse.com/addons/wow/minimap-button-frame-skin-pack", "allowbeta": false, "name": "Minimap Button Frame Skin Pack", "version": "3.0.1b"}, {"uri": "http://www.curse.com/addons/wow/auctionator", "allowbeta": false, "name": "Auctionator", "version": "3.2.6"}, {"uri": "http://www.curse.com/addons/wow/preform-av-enabler", "allowbeta": false, "name": "Preform AV Enabler", "version": "3.04"}, {"uri": "http://www.curse.com/addons/wow/moncaicompare", "allowbeta": false, "name": "Moncai Compare", "version": "v6.2.0"}, {"uri": "http://www.curse.com/addons/wow/tiptacitemref", "allowbeta": false, "name": "TipTacItemRef", "version": "15.03.04"}, {"uri": "http://www.curse.com/addons/wow/metamap", "allowbeta": false, "name": "MetaMap", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/collect_me", "allowbeta": false, "name": "Collect Me", "version": "v2.7.2"}, {"uri": "http://www.curse.com/addons/wow/auc:stat:ilevel", "allowbeta": false, "name": "Auc:Stat:iLevel", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/vuhdo", "allowbeta": false, "name": "VuhDo", "version": "v3.70"}, {"uri": "http://www.curse.com/addons/wow/skada", "allowbeta": false, "name": "Skada Damage Meter", "version": "1.4-32"}, {"uri": "http://www.curse.com/addons/wow/bagnon", "allowbeta": false, "name": "Bagnon", "version": "6.2.4"}, {"uri": "http://www.curse.com/addons/wow/stat-block_memory", "allowbeta": false, "name": "StatBlock_Memory", "version": "r59-release"}, {"uri": "http://www.curse.com/addons/wow/quartz", "allowbeta": false, "name": "Quartz", "version": "3.2.4"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_mailing", "allowbeta": false, "name": "TradeSkillMaster_Mailing", "version": "v2.2.13"}, {"uri": "http://www.curse.com/addons/wow/datastore_talents", "allowbeta": false, "name": "DataStore_Talents", "version": "r50"}, {"uri": "http://www.curse.com/addons/wow/auc-auctioneer-(core)", "allowbeta": false, "name": "Auc-Auctioneer (core)", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/buttontimers", "allowbeta": false, "name": "ButtonTimers", "version": "2.5.17"}, {"uri": "http://www.curse.com/addons/wow/handynotes_draenortreasures", "allowbeta": false, "name": "HandyNotes_DraenorTreasures", "version": "1.11a"}, {"uri": "http://www.curse.com/addons/wow/broker-garrison", "allowbeta": false, "name": "Broker Garrison", "version": "1.8.3"}, {"uri": "http://www.curse.com/addons/wow/auc:stat:simple", "allowbeta": false, "name": "Auc:Stat:Simple", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/bartender4", "allowbeta": false, "name": "Bartender4", "version": "4.6.8"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_additions", "allowbeta": false, "name": "TradeSkillMaster_Additions", "version": "v2.1.6"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_auctioning", "allowbeta": false, "name": "TradeSkillMaster_Auctioning", "version": "v2.4.5"}, {"uri": "http://www.curse.com/addons/wow/recount", "allowbeta": false, "name": "Recount", "version": "v6.1.2d release"}, {"uri": "http://www.curse.com/addons/wow/little-wigs", "allowbeta": false, "name": "LittleWigs", "version": "r1225-release"}, {"uri": "http://www.curse.com/addons/wow/bpl:area-battle-pets-list", "allowbeta": false, "name": "BPL:Area Battle Pets List", "version": "0.2.1"}, {"uri": "http://www.curse.com/addons/wow/metamapcvt", "allowbeta": false, "name": "MetaMapCVT", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/fishing-buddy---tracking-
frame", "allowbeta": false, "name": "Fishing Buddy - Tracking Frame", "version": "1.4w"}, {"uri": "http://www.curse.com/addons/wow/bonusscanner-continued-5.3", "allowbeta": false, "name": "BonusScanner Continued 5.3", "version": "5.4.0"}, {"uri": "http://www.curse.com/addons/wow/auc:stat:std-deviation", "allowbeta": false, "name": "Auc:Stat:Std Deviation", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/handynotes_pettamers", "allowbeta": false, "name": "HandyNotes_PetTamers", "version": "v3"}, {"uri": "http://www.curse.com/addons/wow/slidebar-(lib)", "allowbeta": false, "name": "SlideBar (lib)", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/gtfo", "allowbeta": false, "name": "GTFO", "version": "4.37.5"}, {"uri": "http://www.curse.com/addons/wow/datastore_auctions", "allowbeta": false, "name": "DataStore_Auctions", "version": "r43"}, {"uri": "http://www.curse.com/addons/wow/spellflash_mage", "allowbeta": false, "name": "SpellFlash: Mage", "version": "1.3.94"}, {"uri": "http://www.curse.com/addons/wow/informant", "allowbeta": false, "name": "Informant", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_auctiondb", "allowbeta": false, "name": "TradeSkillMaster_AuctionDB", "version": "v2.7.1"}, {"uri": "http://www.curse.com/addons/wow/stat-block_durability", "allowbeta": false, "name": "StatBlock_Durability", "version": "r32-release"}, {"uri": "http://www.curse.com/addons/wow/mik's-scrolling-battle-text", "allowbeta": false, "name": "Mik's Scrolling Battle Text", "version": "5.7.142"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_wowuction", "allowbeta": false, "name": "TradeSkillMaster_WoWuction", "version": "v2.5.2"}, {"uri": "http://www.curse.com/addons/wow/handynotes_summerfestival", "allowbeta": false, "name": "HandyNotes_SummerFestival", "version": "v1.2"}, {"uri": "http://www.curse.com/addons/wow/auc:scandata", "allowbeta": false, "name": "Auc:ScanData", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/spellflash_xhunter", "allowbeta": false, "name": "SpellFlash: X-Hunter", "version": "1.3"}, {"uri": "http://www.curse.com/addons/wow/timelessislechests", "allowbeta": false, "name": "HandyNotes_TimelessIsleChests", "version": "1.12"}, {"uri": "http://www.curse.com/addons/wow/stubby-(lib)", "allowbeta": false, "name": "Stubby (lib)", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/chatter", "allowbeta": false, "name": "Chatter", "version": "1.4.6"}, {"uri": "http://www.curse.com/addons/wow/metamapbwp", "allowbeta": false, "name": "MetaMapBWP", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/tomtom", "allowbeta": false, "name": "TomTom", "version": "v60200-2.1.0"}, {"uri": "http://www.curse.com/addons/wow/stat-block_folks", "allowbeta": false, "name": "StatBlock_Folks", "version": "r70-release"}, {"uri": "http://www.curse.com/addons/wow/handynotes_specialnpcsetc", "allowbeta": false, "name": "HandyNotes Special NPCs Etc", "version": "v1.1.1-Beta"}, {"uri": "http://www.curse.com/addons/wow/datastore", "allowbeta": false, "name": "DataStore", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_shopping", "allowbeta": false, "name": "TradeSkillMaster_Shopping", "version": "v2.4.6"}, {"uri": "http://www.curse.com/addons/wow/scrap-visualizer", "allowbeta": false, "name": "Scrap Visualizer", "version": "12.24"}, {"uri": "http://www.curse.com/addons/wow/minimap-button-frame", "allowbeta": false, "name": "Minimap Button Frame", "version": "3.1.10e"}, {"uri": "http://www.curse.com/addons/wow/<sgi>-superguildinvite", "allowbeta": false, "name": "<SGI> SuperGuildInvite", "version": "7.5.2"}, {"uri": "http://www.curse.com/addons/wow/tradeskillmaster_accounting", "allowbeta": false, "name": "TradeSkillMaster_Accounting", "version": "v2.4.5"}, {"uri": "http://www.curse.com/addons/wow/spellflash_hunter", "allowbeta": false, "name": "BigRedBrent's 
SpellFlash: Hunter", "version": "2.20.3"}, {"uri": "http://www.curse.com/addons/wow/tb_core", "allowbeta": false, "name": "TB Core", "version": "r151-release"}, {"uri": "http://www.curse.com/addons/wow/lootwhatiwant", "allowbeta": false, "name": "LootWhatIWant", "version": "LootWhatIWant - v6.2.0"}, {"uri": "http://www.curse.com/addons/wow/spellflash_templateaddon", "allowbeta": false, "name": "SpellFlash: Template Module", "version": "3.0.9"}, {"uri": "http://www.curse.com/addons/wow/fishing-buddy", "allowbeta": false, "name": "Fishing Buddy", "version": "1.5.3"}, {"uri": "http://www.curse.com/addons/wow/scrap-options", "allowbeta": false, "name": "Scrap Options", "version": "12.24"}, {"uri": "http://www.curse.com/addons/wow/shadowed-unit-frames", "allowbeta": false, "name": "Shadowed Unit Frames", "version": "v4.0.10"}, {"uri": "http://www.curse.com/addons/wow/datastore_containers", "allowbeta": false, "name": "DataStore_Containers", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/archy", "allowbeta": false, "name": "Archy - Archaeology Assistant", "version": "6.2.2.3"}, {"uri": "http://www.curse.com/addons/wow/spellflash_paladin", "allowbeta": false, "name": "SpellFlash: Paladin", "version": "1.5.2"}, {"uri": "http://www.curse.com/addons/wow/pawn", "allowbeta": false, "name": "Pawn", "version": "1.9.19"}, {"uri": "http://www.curse.com/addons/wow/elvui", "allowbeta": false, "name": "ElvUI", "version": "7.76"}, {"uri": "http://www.curse.com/addons/wow/zygor-guides-viewer-4", "allowbeta": false, "name": "Zygor Guides Viewer 4", "version": "4.0"}, {"uri": "http://www.curse.com/addons/wow/handynotes-higher-learning", "allowbeta": false, "name": "HandyNotes: Higher Learning", "version": "6.2.0.4"}, {"uri": "http://www.curse.com/addons/wow/tradeskill-master", "allowbeta": false, "name": "TradeSkillMaster", "version": "v2.10.26"}, {"uri": "http://www.curse.com/addons/wow/metamapwkb", "allowbeta": false, "name": "MetaMapWKB", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/tidy-plates", "allowbeta": false, "name": "Tidy Plates", "version": "6.17.1"}, {"uri": "http://www.curse.com/addons/wow/saved_instances", "allowbeta": false, "name": "SavedInstances", "version": "6.2.5"}, {"uri": "http://www.curse.com/addons/wow/beancounter", "allowbeta": false, "name": "BeanCounter", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/scrap-merchant", "allowbeta": false, "name": "Scrap Merchant", "version": "12.24"}, {"uri": "http://www.curse.com/addons/wow/handynotes", "allowbeta": false, "name": "HandyNotes", "version": "v1.4.5"}, {"uri": "http://www.curse.com/addons/wow/auc:stat:purchased-stats", "allowbeta": false, "name": "Auc:Stat:Purchased Stats", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/scrap", "allowbeta": false, "name": "Scrap", "version": "12.24"}, {"uri": "http://www.curse.com/addons/wow/datastore_pets", "allowbeta": false, "name": "DataStore_Pets", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/datastore_characters", "allowbeta": false, "name": "DataStore_Characters", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/bittens-spellflash-dk", "allowbeta": false, "name": "Bitten's SpellFlash: DK", "version": "60100.201503092107"}, {"uri": "http://www.curse.com/addons/wow/elvui-config", "allowbeta": false, "name": "ElvUI Config", "version": "1.01"}, {"uri": "http://www.curse.com/addons/wow/clcret", "allowbeta": false, "name": "Retribution FCFS helper (clcret)", "version": "v.1.6.20.001"}, {"uri": "http://www.curse.com/addons/wow/metamapnbk", "allowbeta": false, "name": "MetaMapNBK", "version": "4.3.0"}, {"uri": "http://www.curse.com/addons/wow/spellflashcore", "allowbeta": false, "name": "SpellFlashCore", "version": "2.1.1"}, {"uri": "http://www.curse.com/addons/wow/reforgenator", "allowbeta": false, "name": "Reforgenator", "version": "v2.4.3"}, {"uri": "http://www.curse.com/addons/wow/datastore_quests", "allowbeta": false, "name": "DataStore_Quests", "version": "6.0.002"}, {"uri": 
"http://www.curse.com/addons/wow/tiptacoptions", "allowbeta": false, "name": "TipTacOptions", "version": "15.03.04"}, {"uri": "http://www.curse.com/addons/wow/clique", "allowbeta": false, "name": "Clique", "version": "v60200-1.0.0"}, {"uri": "http://www.curse.com/addons/wow/enchantrix", "allowbeta": false, "name": "Enchantrix", "version": "5.21d2.5561 (SanctimoniousSwamprat)"}, {"uri": "http://www.curse.com/addons/wow/flight-map", "allowbeta": false, "name": "Flight Map and Time", "version": "v6.1.0.0"}, {"uri": "http://www.curse.com/addons/wow/parrot", "allowbeta": false, "name": "Parrot", "version": "v1.12.0"}, {"uri": "http://www.curse.com/addons/wow/gladius-rev-4.1.1", "allowbeta": false, "name": "Gladius rev 4.1.1", "version": "4.1.1"}, {"uri": "http://www.curse.com/addons/wow/datastore_garrisons", "allowbeta": false, "name": "DataStore_Garrisons", "version": "6.0.002"}, {"uri": "http://www.curse.com/addons/wow/ashranbuddy", "allowbeta": false, "name": "AshranBuddy", "version": "v6.2.0a"}, {"uri": "http://www.curse.com/addons/wow/bittens-spellflash-druid", "allowbeta": false, "name": "Bitten's SpellFlash: Druid", "version": "60100.201503092107"}, {"uri": "http://www.curse.com/addons/wow/gatherer-heads-up-display-plugin", "allowbeta": false, "name": "Gatherer Heads-Up Display Plugin", "version": "5.0.0"}, {"uri": "http://www.curse.com/addons/wow/healers-have-to-die", "allowbeta": false, "name": "Healers have to die", "version": "2.3.7"}]

That is the only document in ~/.lcurse, so no settings.cfg

**Comment by ephraim** [comment]
Hey Quintin96,
the file you posted, included newlines or at least the text you posted. I removed them and I removed all the versions which where recognized. After that lcurse could download most of the addons some of them aren't from curse.com, so only possible if you want to use the git repo of them (if available) or not updateable via lcurse. Others werent recognized correctly so, double check the list to include the Addons you use against the list in lcurse. Apart of that, it worked fine for me.
here is the cleaned up file. Just rename it from addons.json.txt to addons.json and place it in your ~/.lcurse folder. Then use the latest lcurse and double check the list.
Regards Ephraim
[addons.json.txt](https://github.com/ephraim/lcurse/files/22718/addons.json.txt)

**Comment by Quintin96** [comment]
Did as you said. Clicked update catalog and now seem to be stuck at 10% (410 addons found)

**Comment by ephraim** [comment]
The catalog functions has nothing to do with your addons. This is just a "grab" of the list of available addons on curse.com. As this function is independend of everything what is on your PC and I just could update my catalog perfectly, I don't know whats wrong.
You can try and start lcurse from console and look if any exception occurs.
Did the update of your addons work?

**Comment by Quintin96** [comment]
No, updating got stuck at 36% this time, but I manually went through each addon and updated, many appeared highlighted in red (Which I assume means that they cannot be updated from curse), but I was able to get most white (I assume means up to date) and a couple did update and highlighted green. Some that are not available on curse and I felt the need to have (like ElvUI) I just went and got manually from the site. Thanks for your help, updating 1 by 1 seems to do the trick, although slightly tedious. Either way would not have been able to do so without lcurse, so thank you :)

**Comment by ephraim** [comment]
There is a difference between "Update Catalog" and "Update All Addons".
What you do one by one is the same as the "Update All Addons" button does.

Red == Error (mostly a 404 for the specified URL)
White == Up to date addon
Green == Addon was updated successfully
Yellow == Addon needs an update (when you did a check for update)

**Comment by Quintin96** [comment]
Yes, I know there is a difference, but even "Update All Addons" does not complete. It will find about 30%, get stuck, then when I close it, it will update those that it found needing update.

**Comment by ephraim** [comment]
hmm ... try with less threads (can be configured in the prefences (Strg+P))

**Comment by Quintin96** [comment]
Okay so changing the amount of threads does work, tried 1, 50, 100 and 1000, all seem to have different results on how far I get - yet to find the sweet spot that allows me to get complete. Thanks for all your assistance, I will keep trying :)
