### ISSUE TITLE
Better addon recognition

### ISSUE THREAD

**Issue by pquerner** [ephraim/lcurse#2]
When having a addon called for example "BindPad" (folder name "bindpad") the program will ask curse for a addon called "bindpad" but when it really is "bind-pad".
I think, - if the result is a 404 on the addon, there should be a fall-back method which checks the addon name seperated with a dash.

-- This is not trivial I think (without reading any file I guess? (Which could make this clear)) --

**Comment by ephraim** [comment]
Hey!
Please have a look at the lcurse v2 branch.
It can be used parallel to v1 as it has its own configuration and addons file.
At first start with no addons you can use "Common->Import Addons" to import addons after you configured your Wow folder within Preferences.
The uri detection and name resolution should work better now!
