### ISSUE TITLE
Does not create "~/.lcurse" folder automatically

### ISSUE THREAD

**Issue by hotice** [ephraim/lcurse#3]
lcurse doesn't create the ~/.lcurse folder automatically which makes the app fail. For instance, this error was displayed after selecting "Update Catalog" on a fresh installation:
```
Traceback (most recent call last):
  File "/home/andrei/lcurse-master/modules/application.py", line 399, in onUpdateCatalogFinished
    with open(defines.LCURSE_ADDON_CATALOG, "w") as c:
FileNotFoundError: [Errno 2] No such file or directory: '/home/andrei/.lcurse/addon-catalog.json'
```

**Comment by ephraim** [comment]
Thanks for your report. Never tried this :) :+1:

**Comment by hotice** [comment]
I just tested it and I can confirm it's fixed. Thank you very much!
