### ISSUE TITLE
Rescan/Update Addons from Folder

### ISSUE THREAD

**Issue by chibbardpm** [ephraim/lcurse#39]
Hello, Great help having this. Thank you so much for making it.
I do have annoyances deleting mods. It would be nice to just manage that definitively by deleting the folders from my /interface directory and have lcurse just re-scan what is in there and remove no-longer existing entries. Is that possible/reasonable?

Thanks

**Comment by phun-ky** [comment]
+1 for this!

**Comment by ephraim** [comment]
The remove addon function was overworked by some folks. Could you try if this fits your needs?

**Comment by ephraim** [comment]
No response anymore. Resolved.
