### ISSUE TITLE
Won't update The Undermine Journal

### ISSUE THREAD

**Issue by mkaito** [ephraim/lcurse#40]
Probably due to the reported version:

![lcurse_undermine](https://cloud.githubusercontent.com/assets/20434/18671905/cf955280-7f3d-11e6-8258-6e7102de20cd.png)

This addon updates twice a week with fresh market data. The actual curse client doesn't seem to have an issue, so perhaps there's something in the manifest you can check?

**Comment by ephraim** [comment]
Hey!
lcurse won't update anything if the version doesn't change. 
But you can enforce an update by removing the version info in the list in lcurse and hit update afterwards.
if you want it automated, create a cronjob which removes the version info from that addon from the addons.json in ~/.lcurse/. This will lead to the result you want.

**Comment by mkaito** [comment]
The reported version is a `YYYYMMDD` timestamp in the curse client though. Maybe they're using a weird field in their manifest. The cronjob would work, but I'm not going to do that. That's just silly. Do you think I should contact the author(s) and bug them about their reported version?

**Comment by ephraim** [comment]
if they append the YYYYMMDD thing to the version 7.0.3.YYYYMMDD would do. lcurse won't look into the manifest as this would need a download of the addon before and when I start to download each addon before lcurse knows the version ....... No way.

**Comment by ephraim** [comment]
and don't try to compare lcurse with the curse client. the curse client uses the curse REST API to get informations about the addons.
lcurse uses their website and parses the displayed info.

**Comment by mkaito** [comment]
How about an option to force an update in the lcurse interface then?

**Comment by ephraim** [comment]
Clear the version field of the specific addon in lcurse gui and hit Ctrl+U
