### ISSUE TITLE
I was wondering if you would be interested in making this work on Windows.

### ISSUE THREAD

**Issue by crborga** [ephraim/lcurse#45]
I was able to get it up and running on Windows by installing the requirements. It fails when I click import addons with a charmap error which seems like it would be simple to fix. My coding is limited though so i'm not sure how to fix it. Also, if I remove some addon it seems to work but I think it would be related to how many are in the addons folder.

```
pip install bs4
pip -m install "C:\Path\to\file\lxml-3.6.4-cp35-cp35m-win32.whl" lxml-3.6.4-cp35-cp35m-win32.whl
pip install PyQt5
python lcurse
```

![lcurse](https://cloud.githubusercontent.com/assets/12742032/20856912/e85ddf58-b8ea-11e6-8031-825e2111b178.jpg)

![errors](https://cloud.githubusercontent.com/assets/12742032/20856902/a76390f6-b8ea-11e6-99f0-7b11e8ac0bd8.jpg)

**Comment by jwhipp** [comment]
I am guessing this being closed means no to a windows version?  The curse client + twitch abomination makes this a really attractive way of managing addons cross-platform.

**Comment by ephraim** [comment]
Have you tried it since the close? ... Except the git part, it should work. At least it worked here at my wifes machine.

**Comment by jwhipp** [comment]
I tried installing python and running the requirements.txt with the main instructions, I ran into issues when it attempted to compile a dependency.    I'll try it again on a fresh machine.  If you're willing to support, I'll post issues that I find and help test.

**Comment by ephraim** [comment]
I'll help as far as I can.
