### ISSUE TITLE
cannot get addon catalog

### ISSUE THREAD

**Issue by sling00** [ephraim/lcurse#47]
Hello,
built the git version on arch linux today and it runs, however when i click update catalog, all I get is this in the console:

retrieved list of addons: 0

**Comment by shinnova** [comment]
Can confirm, having this issue as well after the latest commit ddb630af97f3fda0171fdf576fdbe053237d3954

**Comment by stintel** [comment]
Another confirmation. Reverting ddb630af97f3fda0171fdf576fdbe053237d3954 solves the problem for me.

**Comment by Dissectional** [comment]
https://github.com/ephraim/lcurse/commit/ddb630af97f3fda0171fdf576fdbe053237d3954#commitcomment-20214793

**Comment by shinnova** [comment]
Changing line 28 in `modules/waitdlg.py` to 
`          response = opener.open(urllib.parse.urlparse(urllib.parse.quote(url, ':/?=')).geturl())`
appears to fix the issue. Thank you @steven-jackson and @Dissectional

**Comment by nicdumz** [comment]
Merged, so I believe this could be fixed!

**Comment by stintel** [comment]
Looks good, thanks!

**Comment by oleerik** [comment]
Can confirm that this one is fixed :)
