### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by lifeofdan** [ephraim/lcurse#53]
Hello, I love the program. I am just having trouble installing this on fedora 25. I think it may be a problem with the naming structure of fedora vs ubuntu? I have installed all the dependencies, but it keeps complaining about not having PyQt5. I think fedora may call it "python-qt5". Is there any way to fix this?

**Comment by ephraim** [comment]
Could you please append the console output of a run of lcurse?
Make sure pyqt5 is installed. 
Make sure, that the following line works in python commandline:
`from PyQt5 import Qt`

**Comment by lifeofdan** [comment]
It was user error. I had to do "python3 -m pip install PyQt5" to install PyQt5. I really hate they python version variances. 

Once I did that lcurse ran great. Thanks for the excellent program!

**Comment by ephraim** [comment]
Glad you could fix it!
