### ISSUE TITLE
Issue with PyQt5

### ISSUE THREAD

**Issue by sprice17** [ephraim/lcurse#59]
Complete newb to Python. Been using lcurse for a while and I installed Python (3?) to learn more and broke lcurse I now get the following error:

sprice@xfce:~/Desktop$ lcurse
Traceback (most recent call last):
  File "/usr/bin/lcurse", line 8, in <module>
    from PyQt5 import Qt
**ModuleNotFoundError: No module named 'PyQt5'**

sprice@xfce:~/Desktop$ pip3 install PyQt5
Requirement already satisfied: PyQt5 in /home/sprice/.local/lib/python3.5/site-packages
Requirement already satisfied: sip<4.20,>=4.19.4 in /home/sprice/.local/lib/python3.5/site-packages (from PyQt5)

sprice@xfce:~/Desktop$

**Comment by jwhipp** [comment]
Similar issue here:

"Collecting PyQt5==5.7.* (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement PyQt5==5.7.* (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for PyQt5==5.7.* (from -r requirements.txt (line 3))"

I even tried apt-get install -y python-pyqt5, but I still have the same module error.

**Comment by ephraim** [comment]
Hi,
you need to install pyqt5 for python3, not python 2.

So please try with
apt install python3-pyqt5

That should install the needed module.

**Comment by jwhipp** [comment]
I've been trying to get this running with OSX, ran into this exact same issue even though I pulled in PyQT5 (5.10.1)

➜  lcurse git:(master) brew info pyqt5
pyqt: stable 5.10.1 (bottled)
Python bindings for v5 of Qt
https://www.riverbankcomputing.com/software/pyqt/download5
/usr/local/Cellar/pyqt/5.10.1_1 (985 files, 45MB) *
  Poured from bottle on 2018-07-09 at 13:15:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyqt.rb
==> Dependencies
Required: qt ✔, sip ✔
Recommended: python ✔, python@2 ✔


Any suggestions?
