### ISSUE TITLE
Sometimes lcurse downloads "nolib" version which means the addon needs extra libs and doesn't work

### ISSUE THREAD

**Issue by hotice** [ephraim/lcurse#6]
Sometimes lcurse downloads "nolib" version for some addons, which means the addon needs extra libs and doesn't work.

Some addons have two versions: one includes the libraries required for the addon to run and another version which doesn't need this. Sometimes, the "nolib" version is listed as the latest version - here's an example: http://www.curse.com/addons/wow/tradeskill-master#t1:other-downloads - and if this version is installed, it doesn't work.

One way of fixing this would be to exclude "nolib" versions automatically (but maybe implement an option to allow installing/updating such addons?).

**Comment by ephraim** [comment]
Could you please double check with the latest version. I'm not totally satisfied with this, as you can't install "-nolib" version at all now. But I guess, that most users will install the no"-nolib" versions. So I can live with it for the time being. Until I have an idea how I want this to be solved.

**Comment by hotice** [comment]
It works, thanks! 

I think it should allow -nolib versions if no other version is available (maybe some addons are only available as -nolib).

**Comment by ephraim** [comment]
It just uses the next version if it is named exactly like the nolib version without the nolib part :)
So -nolib will be used in a case if there are only nolib. 
But the no nolib version will always be prefered if available.

Thanks for your issue and testing!

**Comment by hotice** [comment]
Thanks again! You made my WoW Linux experience a lot better with this little tool (and most probably some WebUpd8 readers as well)! :)
