### ISSUE TITLE
Can't remove addon unless Name cell is selected

### ISSUE THREAD

**Issue by hotice** [ephraim/lcurse#8]
If I select an addon by clicking on the URL or version cells and then then from the menu I select "Remove addon", the addon is not removed. This only works if I select the "Name" cell.

Also, why not remove the addon folder when selecting to remove an addon from lcurse, instead of only removing it from lcurse?

**Comment by ephraim** [comment]
can't reproduce :( .... Do you see any errors when you start lcurse in a terminal?

I can't reliably remove the addon, cause the folder doesn't need to be named like the addon and it can have multiple addon folders, like bigwigs (all in one Zip):
BigWigs
BigWigs_BlackrockFoundry
BigWigs_Core
BigWigs_Draenor
BigWigs_HellfireCitadel
BigWigs_Highmaul
BigWigs_Options
BigWigs_Plugins

**Comment by ephraim** [comment]
What do you mean with "remove"

Remove from the list in lcurse?
or
Remove from the list with lcurse restarted?

I just figured, that you need to save the addons list to have the addon completly removed... I probably should trigger a save Addons when removing a addon.

**Comment by hotice** [comment]
I have no idea what happened... but it occured at least twice for me. However, now I can't reproduce it either :) I didn't understand what you mean in your last comment...

Regarding removing the addon folder, how about checking in the addon .toc file for either of these:
```
## X-Curse-Project-Name: 
## X-Curse-Project-ID: 
## X-Curse-Repository-ID: 
```

For instance, all the BigWigs folders that come with the "BigWigs Bossmods" addon have these identical:
```
## X-Curse-Project-Name: BigWigs Bossmods
## X-Curse-Project-ID: big-wigs
## X-Curse-Repository-ID: wow/big-wigs/mainline
```

**Comment by ephraim** [comment]
When you remove an addon from lcurse and close/open lcurse, the addon is back there.
You need to "save addons" before it is really removed.

removing the folder: created an issue for it. ( https://github.com/ephraim/lcurse/issues/9 )

**Comment by hotice** [comment]
Got it but I just tried it and this time I was able to remove an addon without saving it. Weird. Either way, shouldn't this "save addons" be directly integrated and triggered when closing lcurse? I find it kind of confusing :)

**Comment by ephraim** [comment]
done :)

**Comment by hotice** [comment]
Thank you very much! :)
