### ISSUE TITLE
Download link has been modified

### ISSUE THREAD

**Issue by Philmore971** [ephraim/lcurse#81]
The update of the addons was no longer successful. The download link has been modified.
La mise à jour des addons n'aboutit plus. Le lien de téléchargement a été modifié.

**Comment by Ironlenny** [comment]
I don't think the url has changed. I can past the url into my browser and it works fine. I think it's a user-agent issue.

**Comment by Philmore971** [comment]
impossible to do a direct download -> ewample : Details! Damage Meter
tried with
https://www.curseforge.com/wow/addons/details/download
https://www.curseforge.com/wow/addons/details/download/2797484

$ wget https://www.curseforge.com/wow/addons/details/download/2797484
--2019-10-02 02:25:15--  https://www.curseforge.com/wow/addons/details/download/2797484
Résolution de www.curseforge.com (www.curseforge.com)… 104.19.147.132, 104.19.146.132, 2606:4700::6813:9284, ...
Connexion à www.curseforge.com (www.curseforge.com)|104.19.147.132|:443… connecté.
requête HTTP transmise, en attente de la réponse… 403 Forbidden
2019-10-02 02:25:16 erreur 403 : Forbidden.

even forcing on firefox 6
in case this is necessary, emulate a different browser

$ wget --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://www.curseforge.com/wow/addons/details/download/2797484
--2019-10-02 02:30:56--  https://www.curseforge.com/wow/addons/details/download/2797484
Résolution de www.curseforge.com (www.curseforge.com)… 104.19.147.132, 104.19.146.132, 2606:4700::6813:9284, ...
Connexion à www.curseforge.com (www.curseforge.com)|104.19.147.132|:443… connecté.
requête HTTP transmise, en attente de la réponse… 403 Forbidden
2019-10-02 02:30:57 erreur 403 : Forbidden.

**Comment by mboquien** [comment]
FWIW, I have forked the fork of @timwienk and switched to using cloudflare-scrape
 (and fixed another unrelated bug that prevented updates to happen). No guarantee but it seems to be working for me. https://github.com/mboquien/lcurse

**Comment by timwienk** [comment]
@mboquien cool, I did the same thing, but didn't get around to testing it completely yet. good to hear that works.

**Comment by timwienk** [comment]
@mboquien I've added your changes to my PR (with a few small changes on top).

**Comment by Philmore971** [comment]
Dear @mboquien, works perfectly for me ...
However, I manually installed cfscrape on pipenv.
I must now go over my French version completely.

**Comment by timwienk** [comment]
@Philmore971, does #83 help?
